name: Parse Parts Catalog

on:
  workflow_dispatch:
    inputs:
      supplier_slug:
        description: Supplier slug
        required: true
        default: m-pines
      signed_url:
        description: Signed URL to PDF (temporary)
        required: true
        default: https://m-pines.com/wp-content/uploads/2025/06/מחירון-06-25.pdf
      version_date:
        description: Version date (YYYY-MM-DD)
        required: true
        default: 2025-06-01
      source_path:
        description: Raw storage path or label
        required: true
        default: vendor_raw/m-pines/2025-06.pdf

  # Listen to ALL repository_dispatch events (no type filter)
  repository_dispatch: {}

jobs:
  parse:
    runs-on: ubuntu-latest
    env:
      # Secrets
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      # Prefer repository_dispatch payload; else manual inputs; else defaults
      SUPPLIER_SLUG: ${{ github.event.client_payload.supplier_slug || github.event.inputs.supplier_slug || 'm-pines' }}
      SIGNED_URL:    ${{ github.event.client_payload.signed_url    || github.event.inputs.signed_url    || 'https://example.com/file.pdf' }}
      VERSION_DATE:  ${{ github.event.client_payload.version       || github.event.inputs.version_date  || '2025-06-01' }}
      SOURCE_PATH:   ${{ github.event.client_payload.raw_path      || github.event.inputs.source_path   || 'vendor_raw/m-pines/2025-06.pdf' }}
      PARSED_PATH:   ${{ github.event.client_payload.parsed_path   || 'vendor_parsed/m-pines/2025-06.ndjson' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show resolved inputs (debug)
        run: |
          echo "Triggered by: $GITHUB_EVENT_NAME"
          echo "Supplier     : $SUPPLIER_SLUG"
          echo "Version date : $VERSION_DATE"
          echo "Signed URL   : $SIGNED_URL"
          echo "Raw path     : $SOURCE_PATH"
          echo "Parsed path  : $PARSED_PATH"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install requests pdfplumber supabase

# Your repo has a folder named "supabase" which shadows the SDK.
# Rename it during CI so `from supabase import create_client` imports the package.
- name: Avoid local 'supabase' package shadowing
  run: |
    if [ -d "supabase" ]; then mv supabase supabase_project_ci; fi

- name: Run parser
  run: |
    python parse_mpines_fixed.py

